name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'Build' ]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Process Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact: testresults
          name: 'Test Results'
          path: '**/*.trx'
          reporter: dotnet-trx